/** Stored on activity_logs.action — keep in sync with tdtd-frontend if typed there. */
export const ACTIVITY_ACTION = {
  CLASS_CREATED: 'CLASS_CREATED',
  STUDENT_REGISTERED: 'STUDENT_REGISTERED',
  STUDENTS_IMPORTED: 'STUDENTS_IMPORTED',
  ATTENDANCE_SAVED: 'ATTENDANCE_SAVED',
  SCHOOL_YEAR_CREATED: 'SCHOOL_YEAR_CREATED',
  SCHOOL_YEAR_ACTIVATED: 'SCHOOL_YEAR_ACTIVATED',
  SUBJECT_REGISTERED: 'SUBJECT_REGISTERED',
  SUBJECT_UNREGISTERED: 'SUBJECT_UNREGISTERED',
  SUBJECT_ASSIGNED_TO_CLASS: 'SUBJECT_ASSIGNED_TO_CLASS',
  SUBJECT_UNASSIGNED_FROM_CLASS: 'SUBJECT_UNASSIGNED_FROM_CLASS',
  SCORE_EVENT_CREATED: 'SCORE_EVENT_CREATED',
  SCORES_SAVED: 'SCORES_SAVED',
} as const

export type ActivityAction =
  (typeof ACTIVITY_ACTION)[keyof typeof ACTIVITY_ACTION]
